### PR TITLE
[Fix] 홈에서 재생목록 비디오 중복처리 완료, 태그/시간 라벨 다크모드대응, 홈화면 카테고리 테두리변경, 카테고리갱신

### LINKED ISSUE #123: fix: 홈에서 재생목록에 비디오가 중복 추가되고 플레이 리스트 폴더 선택 시 크래시 발생
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Fatal: supplied item identifiers are not unique. Duplicate identifiers: {(
    Media.VideoList.Item.playlist(<PlaylistVideoEntity: 0x60000213ceb0> (entity: PlaylistVideoEntity; id: 0xbb1e22ac0c9e3e41 <x-coredata://9F9C1FF0-60EB-4FD9-B375-9317E8DD2D5E/PlaylistVideoEntity/p16>; data: {
    duration = 11;
    id = 7795;
    likes = 275;
    pageUrl = "https://pixabay.com/videos/id-7795/";
    playlist = "0xbb1e22ac0e7e3e71 <x-coredata://9F9C1FF0-60EB-4FD9-B375-9317E8DD2D5E/PlaylistEntity/p7>";
    tags = "spider, arachnid, insect, octapod, animal, walking spider, wood trunk";
    user = Vfintarts;
    userId = 1055491;
    userImageUrl = "https://cdn.pixabay.com/user/2024/06/17/22-13-06-32_250x250.jpeg";
    video = "0xbb1e22ac0b1e3e51 <x-coredata://9F9C1FF0-60EB-4FD9-B375-9317E8DD2D5E/VideoVariantsEntity/p44>";
    views = 86851;
}))
)}'
terminating due to uncaught exception of type NSException
CoreSimulator 1010.10 - Device: iPhone 16 Pro (116BB221-F99A-4B84-B936-E87F96E23846) - Runtime: iOS 18.2 (22C150) - DeviceType: iPhone 16 Pro
Can't show file for stack frame : <DBGLLDBStackFrame: 0x367758d60> - stackNumber:15 - name:main [inlined] static Media.AppDelegate.$main() -> () [inlined]. The file path does not exist on the file system: /<compiler-generated>

### LINKED ISSUE #139: fix: 홈 셀 태그/duration 라벨 글자 다크모드 대응 안됨

### LINKED ISSUE #149: fix: 홈 화면 태그 테두리 width 줄이기

### LINKED ISSUE #151: fix: 카테고리에 저장하면 홈 태그 갱신 안되는 이슈

### PR DESCRIPTION
**Pull request by jaehun6165**
## #️⃣ Related Issues

close #123
close #139
close #149
close #151 

> ex) #IssueNumber, #IssueNumber

## 📝 Task Details

> Please briefly describe what was worked on in this PR (Images can be attached).

## 💬 Review Requests (Optional)

> If there are specific areas you want the reviewer to focus on, please mention them.

### CODE REVIEW

File: Media/Presentation/Home/HomeViewController.swift [hunk 1]
```diff
@@ -4,9 +4,9 @@ import AVKit
 import AVFoundation
 import CoreData
 
-final class HomeViewController: StoryboardViewController, NavigationBarDelegate {
+final class HomeViewController: StoryboardViewController, NavigationBarDelegate, VideoPlayable {
     private var selectedVideoURL: URL?
-    private var observation: NSKeyValueObservation?
+    var observation: NSKeyValueObservation?
```
Comment (rlarjsdn3) [inline Media/Presentation/Home/HomeViewController.swift:9]: DefaultVideoPlayer() 객체를 가져와야 합니다~ VideoPlayable은 이제 안써요
